---
- hosts: all
  become: yes
  tasks:
  - include: redhat.yml
    when: ansible_facts['os_family']|lower == 'redhat'
  - include: debian.yml
    when: ansible_facts['pkg_mgr']|lower == 'apt'
  - name: "Reboot VM"
    reboot:
  - include: redhat.yml
    when: ansible_facts['os_family']|lower == 'redhat'
  - include: debian.yml
    when: ansible_facts['pkg_mgr']|lower == 'apt'
  - name: "Shutdown VM"
    command: poweroff
